[package]
name = "petgraph-fsm"
version = "0.1.0"
authors = ["Timothy Hobbs"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = {path="../petgraph"}
petgraph-evcxr = {path="../petgraph-evcxr"}
